server:
  port: 9191

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/userrequest
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update